fail_fast: true
repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        always_run: true
        pass_filenames: false
        description: format
        verbose: true
      - id: test
        name: test
        entry: make test
        language: system
        always_run: false
        pass_filenames: false
        description: test
        verbose: true
